version: '3.8'

services:
  db:
    image: mysql:8.0
    deploy:
      resources:
        limits: 
          cpus: '0.5'
          memory: 512M
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Clerical!Schedule6!Ravine"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "Prelaw5!Subsoil!Defraud"
    networks:
      - webnet
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    deploy:
      resources:
        limits: 
          cpus: '0.5'
          memory: 512M
    restart: always
    ports:
      - "80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "Prelaw5!Subsoil!Defraud"
      WORDPRESS_DB_NAME: wordpress
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - webnet

  prometheus:
    depends_on:
      - wordpress
    image: prom/prometheus:v2.30.3
    deploy:
      resources:
        limits: 
          cpus: '0.5'
          memory: 512M
    restart: always
    ports:
      - "9090"
    networks:
      - webnet
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  
  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  grafana:
    depends_on:
      - wordpress
    image: grafana/grafana:latest
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: always
    ports:
      - "3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - webnet
    volumes:
      - grafana_data:/var/lib/grafana

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - webnet
    ports:
      - "80:80"
      - "443:443"

networks:
  webnet:

volumes:
  db_data:
  prometheus_data:
  grafana_data:
